# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipewindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_recipeWindowDialog(object):
    def setupUi(self, recipeWindowDialog):
        recipeWindowDialog.setObjectName("recipeWindowDialog")
        recipeWindowDialog.resize(1009, 436)
        self.horizontalLayout = QtWidgets.QHBoxLayout(recipeWindowDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.queryLayout = QtWidgets.QVBoxLayout()
        self.queryLayout.setObjectName("queryLayout")
        self.recipeNameLineEdit = QtWidgets.QLineEdit(recipeWindowDialog)
        self.recipeNameLineEdit.setObjectName("recipeNameLineEdit")
        self.queryLayout.addWidget(self.recipeNameLineEdit)
        self.queryInputLayout = QtWidgets.QHBoxLayout()
        self.queryInputLayout.setObjectName("queryInputLayout")
        self.queryLineEdit = QtWidgets.QLineEdit(recipeWindowDialog)
        self.queryLineEdit.setObjectName("queryLineEdit")
        self.queryInputLayout.addWidget(self.queryLineEdit)
        self.foodGroupComboBox = QtWidgets.QComboBox(recipeWindowDialog)
        self.foodGroupComboBox.setEnabled(True)
        self.foodGroupComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.foodGroupComboBox.setEditable(True)
        self.foodGroupComboBox.setObjectName("foodGroupComboBox")
        self.queryInputLayout.addWidget(self.foodGroupComboBox)
        self.queryLayout.addLayout(self.queryInputLayout)
        self.resultTableWidget = QtWidgets.QTableWidget(recipeWindowDialog)
        self.resultTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.resultTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resultTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(3)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(2, item)
        self.queryLayout.addWidget(self.resultTableWidget)
        self.horizontalLayout.addLayout(self.queryLayout)
        self.foodRecordLayout = QtWidgets.QVBoxLayout()
        self.foodRecordLayout.setObjectName("foodRecordLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.removeFoodPushButton = QtWidgets.QPushButton(recipeWindowDialog)
        self.removeFoodPushButton.setObjectName("removeFoodPushButton")
        self.horizontalLayout_2.addWidget(self.removeFoodPushButton)
        self.addFoodPushButton = QtWidgets.QPushButton(recipeWindowDialog)
        self.addFoodPushButton.setObjectName("addFoodPushButton")
        self.horizontalLayout_2.addWidget(self.addFoodPushButton)
        self.foodRecordLayout.addLayout(self.horizontalLayout_2)
        self.recordedFoodTableWidget = QtWidgets.QTableWidget(recipeWindowDialog)
        self.recordedFoodTableWidget.setObjectName("recordedFoodTableWidget")
        self.recordedFoodTableWidget.setColumnCount(3)
        self.recordedFoodTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.recordedFoodTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recordedFoodTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recordedFoodTableWidget.setHorizontalHeaderItem(2, item)
        self.foodRecordLayout.addWidget(self.recordedFoodTableWidget)
        self.horizontalLayout.addLayout(self.foodRecordLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(recipeWindowDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox.setObjectName("groupBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(10, 20, 85, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.raise_()
        self.spinBox.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(recipeWindowDialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(recipeWindowDialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(recipeWindowDialog)
        QtCore.QMetaObject.connectSlotsByName(recipeWindowDialog)

    def retranslateUi(self, recipeWindowDialog):
        _translate = QtCore.QCoreApplication.translate
        recipeWindowDialog.setWindowTitle(_translate("recipeWindowDialog", "Dialog"))
        self.recipeNameLineEdit.setText(_translate("recipeWindowDialog", "Recipe Name"))
        self.resultTableWidget.setSortingEnabled(True)
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("recipeWindowDialog", "Food Name"))
        item = self.resultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("recipeWindowDialog", "Description"))
        item = self.resultTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("recipeWindowDialog", "Food Group"))
        self.removeFoodPushButton.setText(_translate("recipeWindowDialog", "Add Food"))
        self.addFoodPushButton.setText(_translate("recipeWindowDialog", "Remove Food "))
        item = self.recordedFoodTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("recipeWindowDialog", "Food Name"))
        item = self.recordedFoodTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("recipeWindowDialog", "Quantity"))
        item = self.recordedFoodTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("recipeWindowDialog", "Units"))
        self.groupBox.setTitle(_translate("recipeWindowDialog", "Serving Size"))
        self.pushButton.setText(_translate("recipeWindowDialog", "Save Recipe"))
        self.pushButton_3.setText(_translate("recipeWindowDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recipeWindowDialog = QtWidgets.QDialog()
    ui = Ui_recipeWindowDialog()
    ui.setupUi(recipeWindowDialog)
    recipeWindowDialog.show()
    sys.exit(app.exec_())

