# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_des_ui/ingredientQuantityDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ingredientQuantityDialog(object):
    def setupUi(self, ingredientQuantityDialog):
        ingredientQuantityDialog.setObjectName("ingredientQuantityDialog")
        ingredientQuantityDialog.resize(1002, 533)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ingredientQuantityDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.queryLayout = QtWidgets.QVBoxLayout()
        self.queryLayout.setObjectName("queryLayout")
        self.foodQuerylabel = QtWidgets.QLabel(ingredientQuantityDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.foodQuerylabel.setFont(font)
        self.foodQuerylabel.setObjectName("foodQuerylabel")
        self.queryLayout.addWidget(self.foodQuerylabel)
        self.queryInputLayout = QtWidgets.QHBoxLayout()
        self.queryInputLayout.setObjectName("queryInputLayout")
        self.queryLineEdit = QtWidgets.QLineEdit(ingredientQuantityDialog)
        self.queryLineEdit.setObjectName("queryLineEdit")
        self.queryInputLayout.addWidget(self.queryLineEdit)
        self.foodGroupComboBox = QtWidgets.QComboBox(ingredientQuantityDialog)
        self.foodGroupComboBox.setEnabled(True)
        self.foodGroupComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.foodGroupComboBox.setEditable(True)
        self.foodGroupComboBox.setObjectName("foodGroupComboBox")
        self.queryInputLayout.addWidget(self.foodGroupComboBox)
        self.queryLayout.addLayout(self.queryInputLayout)
        self.resultTableWidget = QtWidgets.QTableWidget(ingredientQuantityDialog)
        self.resultTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultTableWidget.setAlternatingRowColors(True)
        self.resultTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.resultTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resultTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(1)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        self.resultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.queryLayout.addWidget(self.resultTableWidget)
        self.horizontalLayout_2.addLayout(self.queryLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timeLabel = QtWidgets.QLabel(ingredientQuantityDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout_2.addWidget(self.timeLabel)
        self.consumptionTimeEdit = QtWidgets.QTimeEdit(ingredientQuantityDialog)
        self.consumptionTimeEdit.setObjectName("consumptionTimeEdit")
        self.verticalLayout_2.addWidget(self.consumptionTimeEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.quantityLabel = QtWidgets.QLabel(ingredientQuantityDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.quantityLabel.setFont(font)
        self.quantityLabel.setObjectName("quantityLabel")
        self.verticalLayout_2.addWidget(self.quantityLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quantitySpinBox = QtWidgets.QDoubleSpinBox(ingredientQuantityDialog)
        self.quantitySpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.horizontalLayout.addWidget(self.quantitySpinBox)
        self.unitComboBox = QtWidgets.QComboBox(ingredientQuantityDialog)
        self.unitComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.unitComboBox.setEditable(True)
        self.unitComboBox.setObjectName("unitComboBox")
        self.horizontalLayout.addWidget(self.unitComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.confirmButtonBox = QtWidgets.QDialogButtonBox(ingredientQuantityDialog)
        self.confirmButtonBox.setEnabled(False)
        self.confirmButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.confirmButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirmButtonBox.setObjectName("confirmButtonBox")
        self.verticalLayout_2.addWidget(self.confirmButtonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(ingredientQuantityDialog)
        self.confirmButtonBox.accepted.connect(ingredientQuantityDialog.accept)
        self.confirmButtonBox.rejected.connect(ingredientQuantityDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ingredientQuantityDialog)

    def retranslateUi(self, ingredientQuantityDialog):
        _translate = QtCore.QCoreApplication.translate
        ingredientQuantityDialog.setWindowTitle(_translate("ingredientQuantityDialog", "Dialog"))
        self.foodQuerylabel.setText(_translate("ingredientQuantityDialog", "Search for Foods:"))
        self.resultTableWidget.setSortingEnabled(True)
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ingredientQuantityDialog", "Food Name"))
        self.timeLabel.setText(_translate("ingredientQuantityDialog", "Time of Consumption:"))
        self.quantityLabel.setText(_translate("ingredientQuantityDialog", "Quantity:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ingredientQuantityDialog = QtWidgets.QDialog()
    ui = Ui_ingredientQuantityDialog()
    ui.setupUi(ingredientQuantityDialog)
    ingredientQuantityDialog.show()
    sys.exit(app.exec_())
