# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_des_ui/recipeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_recipeDialog(object):
    def setupUi(self, recipeDialog):
        recipeDialog.setObjectName("recipeDialog")
        recipeDialog.resize(1079, 673)
        recipeDialog.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(recipeDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.queryLayout = QtWidgets.QVBoxLayout()
        self.queryLayout.setObjectName("queryLayout")
        self.recipeNameLineEdit = QtWidgets.QLineEdit(recipeDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recipeNameLineEdit.setFont(font)
        self.recipeNameLineEdit.setAutoFillBackground(True)
        self.recipeNameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.recipeNameLineEdit.setText("")
        self.recipeNameLineEdit.setObjectName("recipeNameLineEdit")
        self.queryLayout.addWidget(self.recipeNameLineEdit)
        self.line_3 = QtWidgets.QFrame(recipeDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.queryLayout.addWidget(self.line_3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.queryLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(recipeDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.queryLayout.addWidget(self.label_3)
        self.queryInputLayout = QtWidgets.QHBoxLayout()
        self.queryInputLayout.setObjectName("queryInputLayout")
        self.queryLineEdit = QtWidgets.QLineEdit(recipeDialog)
        self.queryLineEdit.setObjectName("queryLineEdit")
        self.queryInputLayout.addWidget(self.queryLineEdit)
        self.foodGroupComboBox = QtWidgets.QComboBox(recipeDialog)
        self.foodGroupComboBox.setEnabled(True)
        self.foodGroupComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.foodGroupComboBox.setEditable(True)
        self.foodGroupComboBox.setObjectName("foodGroupComboBox")
        self.queryInputLayout.addWidget(self.foodGroupComboBox)
        self.queryLayout.addLayout(self.queryInputLayout)
        self.resultTableWidget = QtWidgets.QTableWidget(recipeDialog)
        self.resultTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultTableWidget.setAlternatingRowColors(True)
        self.resultTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.resultTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resultTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.resultTableWidget.setColumnCount(1)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        self.resultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.queryLayout.addWidget(self.resultTableWidget)
        self.line_4 = QtWidgets.QFrame(recipeDialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.queryLayout.addWidget(self.line_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.queryLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.quantityLabel = QtWidgets.QLabel(recipeDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.quantityLabel.setFont(font)
        self.quantityLabel.setObjectName("quantityLabel")
        self.gridLayout.addWidget(self.quantityLabel, 0, 0, 1, 1)
        self.unitComboBox = QtWidgets.QComboBox(recipeDialog)
        self.unitComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.unitComboBox.setEditable(True)
        self.unitComboBox.setObjectName("unitComboBox")
        self.gridLayout.addWidget(self.unitComboBox, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(recipeDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.quantitySpinBox = QtWidgets.QDoubleSpinBox(recipeDialog)
        self.quantitySpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.quantitySpinBox.setMaximum(9001.0)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.gridLayout.addWidget(self.quantitySpinBox, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.addFoodPushButton = QtWidgets.QPushButton(recipeDialog)
        self.addFoodPushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFoodPushButton.sizePolicy().hasHeightForWidth())
        self.addFoodPushButton.setSizePolicy(sizePolicy)
        self.addFoodPushButton.setObjectName("addFoodPushButton")
        self.horizontalLayout_4.addWidget(self.addFoodPushButton)
        self.queryLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.queryLayout)
        self.line_2 = QtWidgets.QFrame(recipeDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.foodRecordLayout = QtWidgets.QVBoxLayout()
        self.foodRecordLayout.setObjectName("foodRecordLayout")
        self.label_2 = QtWidgets.QLabel(recipeDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.foodRecordLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.removeFoodPushButton = QtWidgets.QPushButton(recipeDialog)
        self.removeFoodPushButton.setObjectName("removeFoodPushButton")
        self.horizontalLayout_2.addWidget(self.removeFoodPushButton)
        self.foodRecordLayout.addLayout(self.horizontalLayout_2)
        self.recordedFoodTableWidget = QtWidgets.QTableWidget(recipeDialog)
        self.recordedFoodTableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.recordedFoodTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recordedFoodTableWidget.setAlternatingRowColors(True)
        self.recordedFoodTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.recordedFoodTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.recordedFoodTableWidget.setObjectName("recordedFoodTableWidget")
        self.recordedFoodTableWidget.setColumnCount(3)
        self.recordedFoodTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.recordedFoodTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recordedFoodTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recordedFoodTableWidget.setHorizontalHeaderItem(2, item)
        self.recordedFoodTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.recordedFoodTableWidget.horizontalHeader().setStretchLastSection(True)
        self.foodRecordLayout.addWidget(self.recordedFoodTableWidget)
        self.horizontalLayout.addLayout(self.foodRecordLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(recipeDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.servingSizeLabel = QtWidgets.QLabel(recipeDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.servingSizeLabel.setFont(font)
        self.servingSizeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.servingSizeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.servingSizeLabel.setObjectName("servingSizeLabel")
        self.verticalLayout.addWidget(self.servingSizeLabel)
        self.servingSizeSpinBox = QtWidgets.QSpinBox(recipeDialog)
        self.servingSizeSpinBox.setMinimum(0)
        self.servingSizeSpinBox.setProperty("value", 0)
        self.servingSizeSpinBox.setObjectName("servingSizeSpinBox")
        self.verticalLayout.addWidget(self.servingSizeSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.servingSizeLabel_2 = QtWidgets.QLabel(recipeDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.servingSizeLabel_2.setFont(font)
        self.servingSizeLabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.servingSizeLabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.servingSizeLabel_2.setObjectName("servingSizeLabel_2")
        self.verticalLayout.addWidget(self.servingSizeLabel_2)
        self.saveRecipePushButton = QtWidgets.QDialogButtonBox(recipeDialog)
        self.saveRecipePushButton.setEnabled(False)
        self.saveRecipePushButton.setOrientation(QtCore.Qt.Vertical)
        self.saveRecipePushButton.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.saveRecipePushButton.setObjectName("saveRecipePushButton")
        self.verticalLayout.addWidget(self.saveRecipePushButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(recipeDialog)
        self.saveRecipePushButton.accepted.connect(recipeDialog.accept)
        self.saveRecipePushButton.rejected.connect(recipeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(recipeDialog)

    def retranslateUi(self, recipeDialog):
        _translate = QtCore.QCoreApplication.translate
        recipeDialog.setWindowTitle(_translate("recipeDialog", "Dialog"))
        self.recipeNameLineEdit.setPlaceholderText(_translate("recipeDialog", "Recipe Name"))
        self.label_3.setText(_translate("recipeDialog", "Search for Foods:"))
        self.resultTableWidget.setSortingEnabled(True)
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("recipeDialog", "Food Name"))
        self.quantityLabel.setText(_translate("recipeDialog", "Quantity:"))
        self.label.setText(_translate("recipeDialog", "Units:"))
        self.addFoodPushButton.setText(_translate("recipeDialog", "Add Food to Recipe"))
        self.label_2.setText(_translate("recipeDialog", "Ingredient List:"))
        self.removeFoodPushButton.setText(_translate("recipeDialog", "Remove Food from Recipe"))
        item = self.recordedFoodTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("recipeDialog", "Food Name"))
        item = self.recordedFoodTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("recipeDialog", "Quantity"))
        item = self.recordedFoodTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("recipeDialog", "Units"))
        self.servingSizeLabel.setText(_translate("recipeDialog", "Recipe Serving Size"))
        self.servingSizeLabel_2.setText(_translate("recipeDialog", "Save Recipe:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recipeDialog = QtWidgets.QDialog()
    ui = Ui_recipeDialog()
    ui.setupUi(recipeDialog)
    recipeDialog.show()
    sys.exit(app.exec_())

